# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, max_length=5)),
                ('age', models.IntegerField(blank=True)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('bio', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=30)),
                ('avatar', imagekit.models.fields.ProcessedImageField(default='wyqsite/media/uploads/blog/images/406e8ce5e6250118b1497336f4e26950_20180302125310_350.jpg', upload_to='avatar', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
