# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 10:36
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180308_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='uploads/123.jpg', upload_to='uploads', verbose_name='头像'),
        ),
    ]
