# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180308_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10),
        ),
    ]
